### ISSUE TITLE
(질문🙋🏻‍♀️) REST API Response에 들어가야 할 정보

### ISSUE THREAD

**Issue by deingvelop** [searching-project/instagram-searching#31]
우선, 저희는 현재 ResponseDto를 활용하여 다음과 같이 Response를 보내고 있습니다.

- **성공, status `200`**
  ```json
  HTTP/1.1 200 OK
  Content-Type: application/json
  
  {
      "success": true,
      "data": [
          {
              "sid": 4458909,
              "profileName": "john_ms69",
              "businessAccountTF": "false"
          },
          {
              "sid": 3932646,
              "profileName": "_john_collett",
              "businessAccountTF": "false"
          }
      ],
      "error": null
  }
  ```
<br>

- **실패, status `404`**
  ```json
  HTTP/1.1 404 Not Found
  Content-Type: application/json
  
  {
      "success": false,
      "data": null,
      "error": {
          "status": 404,
          "code": "R002",
          "message": "Result Not Found"
      }
  }
  ```
  - code : 조직(여기서는 저희 팀) 자체에서 정한 에러 코드 (이렇게 쓰는 회사도 있다고 들었습니다.)

**Comment by deingvelop** [comment]
### 의문점
저희는 처음 배운 대로 익숙한대로만 해왔는데, 카카오 developers의 API 문서나 네이버 open API를 참고해보았을 때에는 이보다 훨씬 간단하게, data값만 응답하는 것을 확인했습니다. 
- **참고한 사이트**
  - [카카오 developers](https://developers.kakao.com/docs/latest/ko/kakaotalk-channel/rest-api)
  - [네이버 developers](https://developers.naver.com/docs/serviceapi/datalab/shopping/shopping.md#%EC%87%BC%ED%95%91%EC%9D%B8%EC%82%AC%EC%9D%B4%ED%8A%B8-%EA%B0%9C%EC%9A%94)

**Comment by deingvelop** [comment]
### 궁금한 점
1. status code로 `success` 여부를 알 수 있는데, `success` : `true` / `false` 값을 보내야 하는 이유는 잘 모르겠습니다. (실제로 사이드프로젝트를 같이 하는 프론트엔드 친구가 가장 궁금해했습니다...ㅎㅎ)

2. 저 open API에서만 저렇게 군더더기 없이 응답해주는 건지, 실무에서도 `status` = `200`인 경우에는 저렇게 data만 `response body`에 담아 보내는지 궁금합니다.
(= 만약 그렇다면 성공시에는 data만 보내고, 실패일 경우에는 error만 리턴하는지?)

4. `error message` 이외에, 회사 내에서 자체적으로 정한 특수한 `code`도 보통 쓰는지 궁금합니다. (ex: R001, F002 등등..? 혹은 다른 방법?)

5. 우선 저희는 모든 `exception`을 각각 클래스를 만들어서 `RestControllerAdvice`에서 각각 `Handler`를 만들어 관리하고 있는데, 조금 비효율적이고 쓸데 없이 파일이 많은 것 같아서...ㅎㅎ 멘토님께서는 exception 관련 패키지 구조를 어떻게 짜시는지 궁금합니다!

**Comment by J-minkuk** [comment]
1. HttpStatus 코드로 충분히 success를 판단할 수 있는데요.
> 에러를 HttpStatus 200으로 표현하고 내부 data로 판단하는 특수한 경우도 있기는 합니다.

2. 일반적인 케이스는 data만 존재합니다.

3. 에러를 핸들링하는 회사 내부 정책에 따라 다르겠지만, code 값 또는 httpStatus에 따라 FE에서 에러를 핸들링합니다
> alert 노출 메시지 등등

4. RestControllerAdvice
```java
 @ExceptionHandler
    protected ResponseEntity<?> resultNotFoundExceptionHandler(ResultNotFoundException exception) {
        logger.error("resultNotFoundExceptionHandler", exception);
        return new ResponseEntity<>(ResponseDto.fail(RESULT_NOT_FOUND), HttpStatus.NOT_FOUND);
    }

    @ExceptionHandler
    protected ResponseEntity<?> resultExpirationExceptionHandler(ResultExpirationException exception) {
        logger.error("resultExpirationExceptionHandler", exception);
        return new ResponseEntity<>(ResponseDto.fail(RESULT_EXPIRATION), HttpStatus.GONE);
    }

    @ExceptionHandler
    protected ResponseEntity<?> invalidParameterExceptionHandler(InvalidParameterException exception) {
        logger.error("invalidParameterExceptionHandler", exception);
        return new ResponseEntity<>(ResponseDto.fail(INVALID_PARAMETER), HttpStatus.NOT_FOUND);
    }

    @ExceptionHandler
    protected ResponseEntity<?> userNotFoundExceptionHandler(UserNotFoundException exception) {
        logger.error("userNotFoundExceptionHandler", exception);
        return new ResponseEntity<>(ResponseDto.fail(USER_NOT_FOUND), HttpStatus.NOT_FOUND);
    }

    @ExceptionHandler
    protected ResponseEntity<?> postNotFoundExceptionHandler(PostsNotFoundExceptioin exception) {
        logger.error("postNotFoundExceptionHandler", exception);
        return new ResponseEntity<>(ResponseDto.fail(POST_NOT_FOUND), HttpStatus.NOT_FOUND);
    }
```
저도 요거 비스무리하게 해요

**Comment by deingvelop** [comment]
깔끔하게 이해됐습니다. 정말 감사합니다!!!ㅎㅎ
